# Generated by Django 4.1.5 on 2023-06-25 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_summoner_topmasteries"),
    ]

    operations = [
        migrations.AlterField(
            model_name="summoner",
            name="registeredTeams",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="members", to="api.team"
            ),
        ),
        migrations.AlterField(
            model_name="summoner",
            name="registeredTournaments",
            field=models.ManyToManyField(blank=True, null=True, to="api.tournament"),
        ),
        migrations.AlterField(
            model_name="summoner",
            name="requestedTeams",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="requests", to="api.team"
            ),
        ),
    ]
