# Generated by Django 4.1.5 on 2023-06-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_summoner_registeredteams_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="summoner", name="accountID",),
        migrations.AlterField(
            model_name="summoner",
            name="registeredTeams",
            field=models.ManyToManyField(
                blank=True, related_name="members", to="api.team"
            ),
        ),
        migrations.AlterField(
            model_name="summoner",
            name="registeredTournaments",
            field=models.ManyToManyField(blank=True, to="api.tournament"),
        ),
        migrations.AlterField(
            model_name="summoner",
            name="requestedTeams",
            field=models.ManyToManyField(
                blank=True, related_name="requests", to="api.team"
            ),
        ),
    ]
