# Generated by Django 4.1.5 on 2023-07-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_summoner_accountid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="quickJoinQueue",
            field=models.ManyToManyField(blank=True, to="api.summoner"),
        ),
    ]
