# Generated by Django 4.1.5 on 2023-07-24 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_tournament_quickjoinqueue"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="matches",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
