# Generated by Django 4.1.5 on 2023-07-25 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_tournament_matches"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tournament", old_name="matches", new_name="bracket",
        ),
    ]
