# Generated by Django 4.1.5 on 2023-07-30 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_rename_matches_tournament_bracket"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="liveLink",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
