# Generated by Django 4.1.5 on 2023-07-30 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_tournament_livelink"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="description",
            field=models.CharField(
                blank=True, default="No Description", max_length=100
            ),
        ),
    ]
