# Generated by Django 4.1.5 on 2023-08-04 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_tournament_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="summoner",
            name="role",
            field=models.TextField(
                choices=[("user", "user"), ("admin", "admin")],
                default="user",
                max_length=5,
            ),
        ),
    ]
