# Generated by Django 4.1.5 on 2023-08-08 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_summoner_role"),
    ]

    operations = [
        migrations.RemoveField(model_name="tournament", name="ended",),
    ]
