# Generated by Django 4.1.5 on 2023-08-09 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_tournament_omittedteams"),
    ]

    operations = [
        migrations.RemoveField(model_name="tournament", name="omittedTeams",),
    ]
