# Generated by Django 4.1.5 on 2023-08-09 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_remove_tournament_omittedteams"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="teamAcronym",
            field=models.TextField(default="NUL", max_length=3),
        ),
        migrations.AlterField(
            model_name="team",
            name="teamName",
            field=models.TextField(default="Unnamed Team", max_length=100),
        ),
    ]
