# Generated by Django 4.1.5 on 2023-04-29 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tournamentName",
                    models.CharField(default="Unnamed Tournament", max_length=100),
                ),
                (
                    "tournamentFormat",
                    models.TextField(
                        choices=[("1v1", "1v1"), ("5v5", "5v5")],
                        default="5v5",
                        max_length=10,
                    ),
                ),
                (
                    "description",
                    models.CharField(default="No Description", max_length=100),
                ),
                ("participantsCap", models.IntegerField(default=0)),
                ("prizePool", models.FloatField(default=0.0)),
                ("registrationFee", models.FloatField(default=0.0)),
                ("ended", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("teamName", models.TextField(default="Unnamed Team", max_length=100)),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.tournament"
                    ),
                ),
            ],
        ),
    ]
