# Generated by Django 4.1.5 on 2023-04-30 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="openForPublic",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teams",
                to="api.tournament",
            ),
        ),
    ]
