# Generated by Django 4.1.5 on 2023-05-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="rolesFilled",
            field=models.JSONField(
                default={
                    "Bot": None,
                    "Jungle": None,
                    "Mid": None,
                    "Support": None,
                    "Top": None,
                }
            ),
        ),
    ]
