# Generated by Django 4.1.5 on 2023-05-13 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_team_rolesfilled"),
    ]

    operations = [
        migrations.RemoveField(model_name="team", name="pendingRequests",),
        migrations.AddField(
            model_name="summoner",
            name="requestedTeams",
            field=models.ManyToManyField(related_name="requests", to="api.team"),
        ),
        migrations.AlterField(
            model_name="team", name="rolesFilled", field=models.JSONField(default=dict),
        ),
    ]
