# Generated by Django 4.1.5 on 2023-05-02 01:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_team_openforpublic_alter_team_tournament"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tournament", old_name="participantsCap", new_name="teamsCap",
        ),
        migrations.RemoveField(model_name="team", name="openForPublic",),
        migrations.AddField(
            model_name="team", name="members", field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name="team",
            name="teamAcronym",
            field=models.TextField(default="NUL", max_length=3),
        ),
        migrations.AddField(
            model_name="team",
            name="teamJoiningMode",
            field=models.TextField(
                choices=[
                    ("public", "public"),
                    ("request-only", "request-only"),
                    ("invite-only", "invite-only"),
                ],
                default="public",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="startTime",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 2, 1, 41, 56, 955200, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
