# Generated by Django 4.1.5 on 2023-05-02 04:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_participantscap_tournament_teamscap_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="startTime",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 2, 4, 31, 13, 777262, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
