# Generated by Django 4.1.5 on 2023-05-05 01:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_tournament_starttime"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegisteredSummoners",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summonerID", models.TextField(default="No Name", max_length=16)),
            ],
        ),
        migrations.AlterField(
            model_name="tournament",
            name="startTime",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 5, 1, 18, 0, 816506, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
