# Generated by Django 4.1.5 on 2023-05-05 03:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_registeredsummoners_alter_tournament_starttime"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="started",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="startTime",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 5, 3, 5, 36, 552807, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
