# Generated by Django 4.1.5 on 2023-05-06 02:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_tournament_starttime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team", name="members", field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="team",
            name="teamAcronym",
            field=models.TextField(default="NUL", max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="teamName",
            field=models.TextField(default="Unnamed Team", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="startTime",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 6, 2, 42, 21, 20797, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="tournamentName",
            field=models.CharField(
                default="Unnamed Tournament", max_length=100, unique=True
            ),
        ),
    ]
